Ab/newsletter
Ethereum-Costa-Rica/ethereum.cr pull request #10
Opened 2023-09-23 21:26 UTC by brolag

![image](https://github.com/Ethereum-Costa-Rica/ethereum.cr/assets/1393385/2c69cb46-1227-454e-a581-20812ece9ba4)

2023-09-23 21:28 UTC, Coderoostr approved these changes

2023-09-24 23:46 UTC, JustinCast requested changes

2023-09-24 23:46 UTC, JustinCast commented on src/components/Body.tsx
> +                fontWeight={700}
Podemos usar un poco el theme de chakra?

2023-09-24 23:46 UTC, JustinCast commented on src/components/Body.tsx
> +          paddingY={"80px"}
Los brackets no son necesarios en este caso, por tratarse de un string literial

2023-09-24 23:46 UTC, JustinCast commented on src/components/Body.tsx
> +              fontWeight={700}
Quizá todo esto pueda venir del theme

2023-09-25 23:31 UTC, merged